services:
  backend:
    build: ./back-end
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://admin:senha123@database:5432/meu_banco
    depends_on:
      - database
    volumes:
      - ./back-end:/app
    env_file:
      - .env
  database:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"  
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: meu_banco
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./back-end/init.sql:/docker-entrypoint-initdb.d/init.sql


  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"

  frontend:
    build: ./front-end
    ports:
      - "80:80"
    volumes:
      - ./front-end:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  db_data: