services:
  backend:
    build: ./back-end
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/postgres
    depends_on:
      - database
    volumes:
      - ./back-end:/app
    env_file:
      - .env

  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./back-end/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"

  frontend:
    build: ./front-end
    ports:
      - "80:80"
    volumes:
      - ./front-end:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  db_data: